---
title: "Codebook - Getting and Cleaning Data Course Project"
author: "Elizabeth"
date: "23/05/2015"
output: pdf_document
---
This a CodeBook describing variables on Tidy Dataset on the file : ```tidy_data.txt```

+ subjectID          
                    1
            An identifier of the subject who carried out the experiment
                    1 ... 30 Unique identifiers assigned to each subject

+ activityLabel         
                    1
              Activity labels
              1        WALKING
              2   WALKING_UPSTAIRS
              3 WALKING_DOWNSTAIRS
             4            SITTING
              5           STANDING
              6             LAYING
            
            
+  activityID   
                1
            Activity Identifier 
                1 ... 6 Unique to each Activity Label
            
+   timeBodyAccStdX     
                7     
            Standard deviation on the time Body Acceleration Signal - measured on an Accelerometer Device
            (on X-axis))
               -0.9961 ... 0.6269
                       
+ timeBodyAccStdY      
                7     
            Standard deviation on the time Body Acceleration Signal - measured on an Accelerometer Device
            (on Y-axis)
             -0.99024 ... 0.61694
            
+  timeBodyAccStdZ      
                7     
            Standard deviation on the time Body Acceleration Signal - measured on an Accelerometer Device 
            (on Z-axis)
               -0.9877 ... 0.6090 
            
+  timeGravityAccStdX      
                7     
            Standard deviation on the time Gravity Acceleration Signal - measured on an Accelerometer 
            Device (on X-axis)
               -0.9968 ... 0.8296  
            
+  timeGravityAccStdY      
                7     
            Standard deviation on the time Gravity Acceleration Signal - measured on an Accelerometer 
            Device (on Y-axis)
              -0.9942 ... 0.6436    
            
+  timeGravityAccStdZ      
                7     
            Standard deviation on the time Gravity Acceleration Signal - measured on an Accelerometer 
            Device (on Z-axis)
               -0.9910 ... 0.6102 
            
+  timeBodyAccJerkStdX     
                7     
            Standard deviation on the time Body Acceleration Jerk Signal - measured on an Accelerometer
            Device (on X-axis)
               -0.9946 ... 0.5443  
            
+  timeBodyAccJerkStdY       
                7     
            Standard deviation on the time Body Acceleration Jerk Signal - measured on an Accelerometer
            Device (on Y-axis)
               -0.9895 ... 0.3553   
            
+ timeBodyAccJerkStdZ     
                7     
            Standard deviation on the time Body Acceleration Jerk Signal - measured on an Accelerometer
            Device (on Z-axis)
                -0.99329 ... 0.03102      
            
+ timeBodyGyroStdX      
                7     
            Standard deviation on the time Body Acceleration Signal - measured on an Gyroscope 
            Device (on X-axis)
                -0.9943 ... 0.2677 
            
+ timeBodyGyroStdY     
                7     
            Standard deviation on the time Body Acceleration Signal - measured on an Gyroscope 
            Device (on Y-axis)
                -0.9942 ... 0.4765    
            
+ timeBodyGyroStdZ     
                7     
            Standard deviation on the time Body Acceleration Signal - measured on an Gyroscope 
            Device (on Z-axis)
                -0.9855 ... 0.5649               
            
+ timeBodyGyroJerkStdX     
                7     
            Standard deviation on the time Body Acceleration Jerk Signal - measured on an Gyroscope
            Device (on X-axis)
                -0.9965 ... 0.1791        
            
+ timeBodyGyroJerkStdY     
                7     
            Standard deviation on the time Body Acceleration Jerk Signal - measured on an Gyroscope
            Device (on Y-axis)
                -0.9971 ... 0.2959   
            
+ timeBodyGyroJerkStdZ     
                7     
            Standard deviation on the time Body Acceleration Jerk Signal - measured on an Gyroscope 
            Device (on Z-axis)
                -0.9954 ... 0.1932              
  
+ timeBodyAccMagStd   
                7     
            Standard deviation on the time Body Acceleration Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Accelerometer
            Device (obtained by averaging the signals in a signal window sample)
                -0.9865 ... 0.4284   
            
+ timeGravityAccMagStd     
                7     
            Standard deviation on the time Gravity Acceleration Signal with Magnitude 
            calculated ( using the Euclidean norm)- measured on an Accelerometer
            Device (obtained by averaging the signals in a signal window sample)
                -0.9865 ... 0.4284   
            
+ timeBodyAccJerkMagStd   
                7     
            Standard deviation on the time Body Acceleration Jerk Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Accelerometer Device 
            (obtained by averaging the signals in a signal window sample)
                -0.9946 ... 0.4506      
            
+ timeBodyGyroMagStd 
                7     
            Standard deviation on the time Body Acceleration Signal with Magnitude calculated 
            ( using the Euclidean norm) - measured on an Gyroscope Device (obtained by averaging 
            the signals in a signal window sample)
                -0.9814 ... 0.3000    

+ timeBodyGyroJerkMagStd      
                7     
            Standard deviation on the time Body Acceleration Jerk Signal with Magnitude calculated
            ( using the Euclidean norm) - measured on an Gyroscope Device (obtained by averaging the
            signals in a signal window sample)
                -0.9977 ... 0.2502 
            
+ frequencyBodyAccStdX      
                7     
            Standard deviation on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on X-axis)
                -0.9966 ... 0.6585 
            
+ frequencyBodyAccStdY      
                8     
            Standard deviation on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Y-axis)
                -0.99068 ... 0.56019  
            
+ frequencyBodyAccStdZ      
                7     
            Standard deviation on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Z-axis)
                -0.9872 ... 0.6871         
            
+ frequencyBodyAccJerkStdX     
                7     
            Standard deviation on the Body Acceleration Jerk Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on X-axis)
                -0.9951 ... 0.4768     
            
+ frequencyBodyAccJerkStdY     
                7     
            Standard deviation on the Body Acceleration Jerk Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Y-axis)
                -0.9905 ... 0.3498      
            
+ frequencyBodyAccJerkStdZ     
              8     
            Standard deviation on the Body Acceleration Jerk Signal 
            (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Z-axis)
                -0.993108 ... -0.006236  

+ frequencyBodyGyroStdX     
                7     
            Standard deviation on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Gyroscope Device (on X-axis)
                -0.9947 ... 0.1966 
              
+ frequencyBodyGyroStdY    
                7     
            Standard deviation on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Gyroscope Device (on Y-axis)
                -0.9944 ... 0.6462  
            
+ frequencyBodyGyroStdZ      
                7     
            Standard deviation on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Gyroscope Device (on Z-axis)
                -0.9867 ... 0.5225
            
+ frequencyBodyAccMagStd      
                7     
            Standard deviation on the Body Acceleration Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Accelerometer Device
            (obtained by averaging the signals in a signal window sample)
                -0.9876 ... 0.1787 

+ frequencyBodyAccJerkMagStd     
                7     
            Standard deviation on the Body Acceleration Jerk Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Accelerometer Device
            (obtained by averaging the signals in a signal window sample)
                -0.9944 ... 0.3163
            
+ frequencyBodyGyroMagStd  
                7     
            Standard deviation on the Body Acceleration Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Gyroscope Device
            (obtained by averaging the signals in a signal window sample)
                -0.9815 ... 0.2367   
            
+ frequencyBodyGyroJerkMagStd   
                7     
            Standard deviation on the Body Acceleration Jerk Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Gyroscope Device
            (obtained by averaging the signals in a signal window sample)
                -0.9815 ... 0.2367             
            
 + timeBodyAccMeanX      6     
            Mean value on the time Body Acceleration Signal - measured on an Accelerometer Device
            (on X-axis))
            0.2216 ... 0.3015  

+ timeBodyAccMeanY     
                8     
            Mean value on the time Body Acceleration Signal - measured on an Accelerometer Device
            (on Y-axis))
                -0.040514 ... -0.001308
            
+ timeBodyAccMeanZ    
                8     
            Mean value on the time Body Acceleration Signal - measured on an Accelerometer Device
            (on Z-axis))
                -0.15251 ... -0.07538 
            
+ timeGravityAccMeanX    
                7     
            Mean value on the time Gravity Acceleration Signal - measured on an Accelerometer Device
            (on X-axis))
                -0.6800 ... 0.9745             
            
+ timeGravityAccMeanY      
                8     
            Mean value on the time Gravity Acceleration Signal - measured on an Accelerometer Device
            (on Y-axis))
                -0.47989 ... 0.95659   
            
+ timeGravityAccMeanZ      
                8     
            Mean value on the time Gravity Acceleration Signal - measured on an Accelerometer Device
            (on Z-axis))
                -0.49509 ... 0.95787              
  
+ timeBodyAccJerkMeanX      
                8     
            Mean value on the time Body Acceleration Jerk Signal - measured on an Accelerometer Device
            (on Z-axis))
                -0.04269 ... 0.13019   

+ timeBodyAccJerkMeanY     
                10     
            Mean value on the time Body Acceleration Jerk Signal - measured on an Accelerometer Device
            (on Y-axis))
                -0.0386872 ...  0.0568186
            
+ timeBodyAccJerkMeanZ     
                9     
            Mean value on the time Body Acceleration Jerk Signal - measured on an Accelerometer Device
            (on Z-axis))
                -0.067458 ...  0.038053 
            
+ timeBodyGyroMeanX      
                8     
            Mean value on the time Body Acceleration Signal - measured on an Gyroscope Device
            (on X-axis))
            -0.20578 ... 0.19270
            
+ timeBodyGyroMeanY      8     
            Mean value on the time Body Acceleration Signal - measured on an Gyroscope Device
            (on Y-axis))
                -0.20421 ... 0.02747 
            
+ timeBodyGyroMeanZ
                8     
            Mean value on the time Body Acceleration Signal - measured on an Gyroscope Device
            (on Z-axis))
                -0.07245 ... 0.17910   
            
+ timeBodyGyroJerkMeanX      
                8     
            Mean value on the time Body Acceleration Jerk Signal - measured on an Gyroscope Device
            (on X-axis))
            -0.15721 ... -0.02209  
            
+ timeBodyGyroJerkMeanY      
               8     
            Mean value on the time Body Acceleration Jerk Signal - measured on an Gyroscope Device
            (on Y-axis))
                -0.07681 ... -0.01320  
            
+ timeBodyGyroJerkMeanZ     
                9     
            Mean value on the time Body Acceleration Jerk Signal - measured on an Gyroscope Device
            (on Z-axis))
                -0.092500 ... -0.006941
            
+ timeBodyAccMagMean      
                7     
            Mean value on the time Body Acceleration Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Accelerometer
            Device (obtained by averaging the signals in a signal window sample)
                -0.9865 ... 0.6446      
            
+ timeGravityAccMagMean     
                7     
            Mean value on the time Gravity Acceleration Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Accelerometer
            Device (obtained by averaging the signals in a signal window sample)
                -0.9865 ... 0.6446  
            
+ timeBodyAccJerkMagMean    
                7     
            Mean value on the time Body Acceleration Jerk Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Accelerometer
            Device (obtained by averaging the signals in a signal window sample)
                -0.9928 ... 0.4345              
            
+ timeBodyGyroMagMean      
                7     
            Mean value on the time Body Acceleration Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Gyroscope
            Device (obtained by averaging the signals in a signal window sample)
                -0.9807 ... 0.4180   
            
+ timeBodyGyroJerkMagMean      
                8     
            Mean value on the time Body Acceleration Jerk Signal with Magnitude 
            calculated ( using the Euclidean norm) - measured on an Gyroscope
            Device (obtained by averaging the signals in a signal window sample)
                -0.99732 ... 0.08758  
            
+ frequencyBodyAccMeanX      
                7     
            Mean value on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on X-axis)
                -0.9952 ... 0.5370 
            
+ frequencyBodyAccMeanY     
                8     
            Mean value on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Y-axis)
                -0.98903 ... 0.52419   
            
+ frequencyBodyAccMeanZ      
                7     
            Mean value on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Z-axis)
                -0.9895 ... 0.2807    
            
+ frequencyBodyAccJerkMeanX     
                7     
            Mean value on the Body Acceleration Jerk Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on X-axis)
                -0.9946 ... 0.4743    
            
+ frequencyBodyAccJerkMeanY      
                7     
            Mean value on the Body Acceleration Jerk Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Y-axis)
                -0.9894 ... 0.2767   
            
+ frequencyBodyAccJerkMeanZ      
                7     
            Mean value on the Body Acceleration Jerk Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Accelerometer Device (on Z-axis)
                -0.9920 ...  0.1578
 
+ frequencyBodyGyroMeanX     
                7     
            Mean value on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Gyroscope Device (on X-axis)
                -0.9931 ...  0.4750
            
+ frequencyBodyGyroMeanY      
                7     
            Mean value on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Gyroscope Device (on Y-axis)
                -0.9940 ...   0.3288 
            
+ frequencyBodyGyroMeanZ     
                7     
            Mean value on the Body Acceleration Signal (with Fast Fourier Transform (FFT) applied 
            on measurement) - measured on an Gyroscope Device (on Z-axis)
                -0.9860 ...    0.4924             
            
+ frequencyBodyAccMagMean     
                7     
            Mean value on the Body Acceleration Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Accelerometer Device
            (obtained by averaging the signals in a signal window sample)
                -0.9868 ... 0.5866     
            
+ frequencyBodyAccJerkMagMean  
                7     
            Mean value on the Body Acceleration Jerk Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Accelerometer Device
            (obtained by averaging the signals in a signal window sample)
                -0.9940 ... 0.5384    
            
+ frequencyBodyGyroMagMean    
                7     
            Mean value on the Body Acceleration Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Gyroscope Device
            (obtained by averaging the signals in a signal window sample)
                -0.9865 ... 0.2040   
            
+frequencyBodyGyroJerkMagMean    
                7     
            Mean value on the Body Acceleration Jerk Signal with Magnitude
            calculated ( using the Euclidean norm) and with Fast Fourier Transform (FFT) applied 
            on the measurement - measured on an Gyroscope Device
            (obtained by averaging the signals in a signal window sample)
                -0.9976 ... 0.1466             
 
